### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by ritalinn** [ChuckDaniels87/rnr#13]
Hello. I am a designer. I can design a logo for you. If you like it, I'll give it a gift.

**Comment by ChuckDaniels87** [comment]
I've been thinking about this since I also have some limited experience creating some icons for Numix Icon Theme. Feel free to post here some logo ideas and we can discuss them.

Some hints of what I would like:
* Something simple, flat (or pseudo-flat) and symbolic.
* *RnR* is related to both "**R**e**N**ame**R**" and "**R**ock '**N**' **R**oll".
* [`bat` logo](https://github.com/sharkdp/bat) is quite cool.

Thank very much!!

**Comment by ChuckDaniels87** [comment]
I finally created a logo for `rnr`:

<img src="https://user-images.githubusercontent.com/8478202/107156909-59030580-6981-11eb-9374-95959b6ec067.png" width="300" height="300">
