### ISSUE TITLE
regexp in windows 

### ISSUE THREAD

**Issue by mikowiec** [ChuckDaniels87/rnr#21]
precondition:
- windows 7 x86

Pattern "strin"  should be changed to pattern "strout" in current directory
Does not work next command
`rnr -n -r strin strout ./*`
but the workaround with recursive option and dept=1 works well:
`rnr -n -r -d 1  strin strout ./`

next issue  
regexp with single quotes does not work correct, 
`rnr -n -r -d 1  '(.+)\.d(\w+)' '${1}' ./`
but double quotes works well
`rnr -n -r -d 1  "(.+)\.d(\w+)" "${1}" ./`

**Comment by ChuckDaniels87** [comment]
I would need to know a bit more about how you are using `rnr`:
- Version of `rnr`.
- Shell/Console version, are you using `cmd.exe` or PowerShell?

> Does not work next command
`rnr -n -r strin strout ./*`
but the workaround with recursive option and dept=1 works well:
`rnr -n -r -d 1 strin strout ./`

As I can see in your first command, you are using `*` wildcard and not in the second one. The first command should be the same as `rnr -n -r strin strout ./` since you are using the recursive flag.

Also, Windows shells do not expand `*` to the application as in Unix-like systems, you can read more about [here](https://superuser.com/a/460609). However, if you are using PowerShell you could expand the list of files using `rnr -r strin strout (Get-Item ./*)`

> next issue
regexp with single quotes does not work correct,
`rnr -n -r -d 1 '(.+)\.d(\w+)' '${1}' ./`
but double quotes works well
`rnr -n -r -d 1 "(.+)\.d(\w+)" "${1}" ./`

If you are using `cmd.exe` in Windows, you cannot use `'` since it will pass that character explicitly, you need to use always `"`. In PowerShell you can use both.

**Comment by ChuckDaniels87** [comment]
@mikowiec Feel free to open the issue again if you have further problems.
